name: Not really First
on: push
jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: cloning source code
        uses: actions/checkout@v6

      - name: display start message
        run: echo "Formatting and Lintining in the process!!"

      - name: installing uv
        run: pip install uv

      - name: sync uv
        run: uv sync
      
      - name: Run checks
        run: |
          uv run ruff check .
          uv run ruff format --check .

  create_docker_image:
    runs-on: ubuntu-latest
      steps:
      - name: cloning source code
        uses: actions/checkout@v6

      - name: build docker image
        run: docker build . 
      
      - name: show docker containers
        run: docker image ls
      